CREATE TABLE OLAP_Fato_Compra
(
    ID_Compra INT NOT NULL,
    ID_Estado_Civil INT NOT NULL,
    ID_Local INT NOT NULL,
    ID_Tempo INT NOT NULL,
    ID_Aparelho INT NOT NULL,
    Valor FLOAT NOT NULL,
    Quantidade  INT NOT NULL
);
ALTER TABLE OLAP_Fato_Compra ADD CONSTRAINT PK_OLAP_Fato_Compra PRIMARY KEY (ID_Compra);

CREATE TABLE OLAP_Dim_Local
(
    ID_Local  INT NOT NULL,
    Cidade VARCHAR(30) NOT NULL,
    Estado CHAR(2) NOT NULL
);
ALTER TABLE OLAP_Dim_Local ADD CONSTRAINT PK_OLAP_Dim_Local PRIMARY KEY (ID_Local);
CREATE SEQUENCE SQ_OLAP_Local;

CREATE TABLE OLAP_Dim_Tempo
(
    ID_Tempo INT NOT NULL,
    Quadrimestre INT NOT NULL,
    Ano INT NOT NULL
);
ALTER TABLE OLAP_Dim_Tempo ADD CONSTRAINT PK_OLAP_Dim_Tempo PRIMARY KEY (ID_Tempo);
CREATE SEQUENCE SQ_OLAP_Tempo;

CREATE TABLE OLAP_Dim_Estado_Civil
(
    ID_Estado_Civil INT NOT NULL,
    Descricao VCHAR(30) NOT NULL
);
ALTER TABLE OLAP_Dim_Estado_Civil ADD CONSTRAINT PK_OLAP_DIM_Estado_CIVIL PRIMARY KEY (ID_Estado_Civil);
CREATE SEQUENCE SQ_OLAP_Estado_Civil;

CREATE TABLE OLAP_Dim_Aparelho
(
    ID_Aparelho INT NOT NULL,
    Modelo VARCHAR(30) NOT NULL,
    Marca VARCHAR(30) NOT NULL
);
ALTER TABLE OLAP_Dim_Aparelho ADD CONSTRAINT PK_OLAP_Dim_Aparelho PRIMARY KEY (ID_Aparelho);
CREATE SEQUENCE SQ_OLAP_Aparelho;

ALTER TABLE OLAP_Fato_Compra ADD CONSTRAINT FK_OLAP_Compra_Local FOREIGN KEY (ID_Local) REFERENCES OLAP_Dim_Local(ID_Local);
ALTER TABLE OLAP_Fato_Compra ADD CONSTRAINT FK_OLAP_Compra_Tempo FOREIGN KEY (ID_Tempo) REFERENCES OLAP_Dim_Tempo(ID_Tempo);
ALTER TABLE OLAP_Fato_Compra ADD CONSTRAINT FK_OLAP_Compra_Estado_Civil FOREIGN KEY (ID_Estado_Civil) REFERENCES OLAP_Dim_Estado_Civil(ID_Estado_Civil);
ALTER TABLE OLAP_Fato_Compra ADD CONSTRAINT FK_OLAP_Compra_Aparelho FOREIGN KEY (ID_Aparelho) REFERENCES OLAP_Dim_Aparelho(ID_Aparelho);
CREATE SEQUENCE SQ_OLAP_Compra;

-- CORREÇÕES DDL OLTP
ALTER TABLE CLIENTES ADD ESTADO_CIVIL VARCHAR(30);

