
-- TRANSFERINDO LOCAIS
INSERT INTO OLAP_Dim_Local (ID_Local, Cidade, Estado)
SELECT C.ID_CIDADE, C.DESCRICAO, E.SIGLA  
FROM Cidade C 
JOIN Estado E USING (ID_Estado) 
WHERE C.DESCRICAO <> 'SSA' AND C.DESCRICAO <> 'SP';

COMMIT;



-- TRANSFERINDO APARELHOS
INSERT INTO OLAP_Dim_Aparelho (ID_Aparelho, Modelo, Marca)
SELECT 
    SQ_OLAP_Aparelho.NEXTVAL, 
    SUB.Modelo, 
    SUB.Marca
FROM (
    SELECT DISTINCT MO.DESCRICAO AS Modelo, MA.DESCRICAO AS Marca
    FROM APARELHO A
    JOIN Modelo MO ON A.ID_Modelo = MO.ID_Modelo
    JOIN Marca MA ON MO.ID_Marca = MA.ID_Marca
) SUB
WHERE NOT EXISTS (
    SELECT 1 FROM OLAP_Dim_Aparelho T
    WHERE T.Modelo = SUB.Modelo AND T.Marca = SUB.Marca
);
COMMIT;

-- TRANSFERINDO DATAS
INSERT INTO OLAP_Dim_Tempo (ID_Tempo, Ano, Quadrimestre)
SELECT 
    SQ_OLAP_Tempo.NEXTVAL,
    Ano,
    Quadrimestrre
FROM (
    SELECT DISTINCT
        EXTRACT(YEAR FROM DATA) AS Ano,
        CASE 
            WHEN EXTRACT(MONTH FROM DATA) BETWEEN 1 AND 4 THEN 1
            WHEN EXTRACT(MONTH FROM DATA) BETWEEN 5 AND 8 THEN 2
            WHEN EXTRACT(MONTH FROM DATA) BETWEEN 9 AND 12 THEN 3
        END AS Quadrimestrre
    FROM COMPRA
) SUB;

SELECT DISTINCT EXTRACT(YEAR FROM C.Data) AS Ano,
       CASE  
           WHEN EXTRACT(MONTH FROM C.Data) BETWEEN 1 AND 4 THEN 1  
           WHEN EXTRACT(MONTH FROM C.Data) BETWEEN 5 AND 8 THEN 2  
           ELSE 3  
       END AS Quadrimestre
FROM COMPRA C;
COMMIT;

-- TRANSFERINDO ESTADO CIVIL
INSERT INTO OLAP_Dim_Estado_Civil (ID_Estado_Civil, Descricao) VALUES (1, 'Casado');
INSERT INTO OLAP_Dim_Estado_Civil (ID_Estado_Civil, Descricao) VALUES (2, 'Solteiro');
COMMIT;

--TRANSFERINDO TODOS OS DADOS PARA FATO_COMPRA
INSERT INTO OLAP_Fato_Compra (ID_Compra, ID_Local, ID_Tempo, ID_Estado_Civil, ID_Aparelho, Valor, Quantidade)
SELECT 
    SQ_OLAP_Compra.NEXTVAL,  
    ODL.ID_Local,  
    ODT.ID_Tempo,  
    ODEC.ID_Estado_Civil,
    ODA.ID_Aparelho,
    CR.VALOR,  
    CR.QUANTIDADE  
FROM CARRINHO CR
JOIN COMPRA C ON CR.ID_COMPRA = C.ID_COMPRA
JOIN CLIENTE CLT ON C.ID_CLIENTE = CLT.ID_CLIENTE

-- Dimensão Estado Civil (Escolhe um único registro)
JOIN (SELECT DISTINCT ID_Estado_Civil, Descricao FROM OLAP_Dim_Estado_Civil) ODEC 
ON UPPER(TRIM(ODEC.Descricao)) = UPPER(TRIM(CLT.ESTADO_CIVIL))

-- Dimensão Local (Escolhe um único registro)
JOIN (SELECT DISTINCT ID_Local, Cidade, Estado FROM OLAP_Dim_Local) ODL 
ON ODL.Cidade = (SELECT CD.DESCRICAO FROM CIDADE CD WHERE CD.ID_CIDADE = CLT.ID_CIDADE) 
AND ODL.Estado = (SELECT ES.SIGLA FROM ESTADO ES WHERE ES.ID_ESTADO = 
                 (SELECT CD.ID_ESTADO FROM CIDADE CD WHERE CD.ID_CIDADE = CLT.ID_CIDADE))

-- Dimensão Tempo (Garante um único valor por tempo)
JOIN OLAP_Dim_Tempo ODT  
ON ODT.Ano = EXTRACT(YEAR FROM C.Data)
AND ODT.Quadrimestre =  
    CASE  
        WHEN EXTRACT(MONTH FROM C.Data) BETWEEN 1 AND 4 THEN 1  
        WHEN EXTRACT(MONTH FROM C.Data) BETWEEN 5 AND 8 THEN 2  
        ELSE 3  
    END

-- Dimensão Aparelho (Escolhe um único modelo por compra)
JOIN (SELECT DISTINCT ID_Aparelho, Modelo FROM OLAP_Dim_Aparelho) ODA 
ON UPPER(TRIM(ODA.Modelo)) = UPPER(TRIM(
    (SELECT ML.DESCRICAO FROM MODELO ML WHERE ML.ID_MODELO = 
     (SELECT A.ID_MODELO FROM APARELHO A WHERE A.ID_APARELHO = CR.ID_APARELHO))
));
COMMIT;


-- CORREÇÕES DML OLTP
UPDATE CLIENTE SET ID_Cidade = 5 WHERE ID_Cidade = 30;
UPDATE CLIENTE SET ID_Cidade = 19 WHERE ID_Cidade = 37;
UPDATE CLIENTE SET ID_Cidade = 25 WHERE ID_Cidade = 35;

UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 1;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 2;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 3;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 4;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 5;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 6;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 7;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 8;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 9;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 10;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 11;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 12;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 13;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 14;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 15;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 16;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 17;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 18;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 19;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 20;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 21;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 22;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 23;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 24;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 25;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 26;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 27;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 28;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 29;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 30;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 31;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 32;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 33;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 34;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 35;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 36;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 37;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 38;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 39;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 40;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 41;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 42;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 43;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 44;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 45;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 46;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 47;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 48;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 49;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 50;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 51;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 52;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 53;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 54;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 55;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 56;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 57;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 58;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 59;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 60;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 61;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 62;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 63;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 64;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 65;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 66;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 67;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 68;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 69;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 70;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 71;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 72;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 73;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 74;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 75;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 76;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 77;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 78;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 79;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 80;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 81;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 82;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 83;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 84;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 85;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 86;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Solteiro' WHERE ID_Cliente = 87;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 88;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 89;
UPDATE CLIENTE SET ESTADO_CIVIL = 'Casado' WHERE ID_Cliente = 90;

COMMIT;